"""
ImageSequence Protocol Buffer (Autogenerated)

Defines protobuf messages for representing image sequences used in animation or visual playback.
DO NOT EDIT: This file is auto-generated by the protocol buffer compiler.
"""

import sys
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

# === Descriptor Definition ===
DESCRIPTOR = _descriptor.FileDescriptor(
    name='image_sequence.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=(
        b'\n\x14image_sequence.proto".\n\tImageData\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08filename\x18\x02 \x01(\t"q\n\rImageSequence\x12\x13\n\x0bsequence_id\x18\x01 \x01(\x03\x12\x15\n\rsequence_type\x18\x02 \x01(\t\x12\x1a\n\x06images\x18\x03 \x03(\x0b\x32\n.ImageData\x12\x18\n\x10playing_interval\x18\x04 \x01(\x02b\x06proto3'
    )
)

# === ImageData Message ===

_IMAGEDATA = _descriptor.Descriptor(
    name='ImageData',
    full_name='ImageData',
    filename=None,
    file=DESCRIPTOR,
    fields=[
        _descriptor.FieldDescriptor(
            name='content', full_name='ImageData.content', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None),
        _descriptor.FieldDescriptor(
            name='filename', full_name='ImageData.filename', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None),
    ],
    nested_types=[],
    enum_types=[],
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_options=None,
)

# === ImageSequence Message ===

_IMAGESEQUENCE = _descriptor.Descriptor(
    name='ImageSequence',
    full_name='ImageSequence',
    filename=None,
    file=DESCRIPTOR,
    fields=[
        _descriptor.FieldDescriptor(
            name='sequence_id', full_name='ImageSequence.sequence_id', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None),
        _descriptor.FieldDescriptor(
            name='sequence_type', full_name='ImageSequence.sequence_type', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value="",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None),
        _descriptor.FieldDescriptor(
            name='images', full_name='ImageSequence.images', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None),
        _descriptor.FieldDescriptor(
            name='playing_interval', full_name='ImageSequence.playing_interval', index=3,
            number=4, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=0.0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None),
    ],
    nested_types=[],
    enum_types=[],
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_options=None,
)

_IMAGESEQUENCE.fields_by_name['images'].message_type = _IMAGEDATA

DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
DESCRIPTOR.message_types_by_name['ImageSequence'] = _IMAGESEQUENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageData = _reflection.GeneratedProtocolMessageType(
    'ImageData', (_message.Message,), {
        'DESCRIPTOR': _IMAGEDATA,
        '__module__': 'image_sequence_pb2'
    }
)
_sym_db.RegisterMessage(ImageData)

ImageSequence = _reflection.GeneratedProtocolMessageType(
    'ImageSequence', (_message.Message,), {
        'DESCRIPTOR': _IMAGESEQUENCE,
        '__module__': 'image_sequence_pb2'
    }
)
_sym_db.RegisterMessage(ImageSequence)

# @@protoc_insertion_point(module_scope)
